export const cities=[
    "Delhi",
    "Gurgaon",
    "Bangalore",
    "Pune",
    "Ahmedabad",
    "Mumbai",
    "Thane",
    "Nashik",
    "Kolkata",
    "Lucknow",
    "Noida",
    "Faridabad",
    "Prayagraj",
    "Patna",
    "Ranchi",
    "Jaipur",
    "Agra",
    "Chandigarh",
    "Nagpur",
    "Chennai",
    "Bhopal",
    "Indore",
    "Hyderabad",
    "Kerala",
    "Bihar",
    "Gujarat",
    "Maharashtra",
    "Karnataka",
    "Madhya Pradesh",
    "Orissa",
    "Uttar Pradesh",
    "Telangana",
    "Andhra Pradesh",
    "Chhatisgarh",
    "Tamil Nadu",
    "West Bengal",
    "Haryana",
    "Uttrakhand",
    "J&K",
    "Himachal Pradesh",
    "Jharkhand",
    "Rajasthan",
    "Goa",
    "Assam",
    "Punjab",
    "Saurashtra & South Gujarat",
    "Uttar Pradesh East",
    "Uttar Pradesh West",
    "Bundelkhand",
    "Other",
  ];
